name: OpenShift 3.0.2 offline image with demo
maintainers:
- Jim Minter <jminter@redhat.com>
description: |
  This image provides an all-in-one instance of OpenShift 3.0.2, including the
  master and node components, examples, GUI and web browser.  All S2I builder
  images are also included, and source code and dependencies for all examples
  apps is pre-downloaded, so no nothing extra is needed and the image can be
  run disconnected from the internet.  This image also includes all the
  components necessary for an OpenShift 3.0.2 demo.

  This image is heavily modified and additionally includes JBoss Developer
  Studio.  It is intended for SAs in order to demo the full OpenShift end-user
  experience.
