name: Red Hat OpenStack Platform 7 image
maintainers:
- Pat Carey <pcarey@redhat.com>
description: |
  This image provides an all-in-one instance of Red Hat OpenStack Platform 7.
layer:
  cpus: 2
  mem: 8192
  nested: "true"
